export const content = ["./index.html", "./src/**/*.{ts,tsx}"];
export const theme = {
  extend: {
    fontFamily: {
      playfair: ["'Playfair Display'", "serif"],
      lora: ["Lora", "serif"],
      orbitron: ["Orbitron", "sans-serif"],
      inter: ["Inter", "sans-serif"],
      poppins: ["Poppins", "sans-serif"],
    },
    colors: {
      // === YENİ SARI/ALTIN TEMA - SİYAH ARKA PLAN ===
      "pong-bg": "#000000",
      "pong-primary": "#e5e5e5",
      "pong-accent": "#fbbf24",
      "pong-secondary": "#f59e0b",
      "pong-highlight": "#eab308",
      "pong-dark-bg": "#0a0a0a",
      "pong-dark-primary": "#d4d4d4",
      "pong-dark-accent": "#fcd34d",
      "pong-dark-secondary": "#fbbf24",
      "pong-dark-highlight": "#ca8a04",
      "pong-gold": "#fbbf24",
      "pong-light-bg": "#111111",
      "pong-sport-primary": "#eab308",
      "pong-sport-accent": "#fde047",
      "pong-sport-bg": "#050505",
      "pong-sport-surface": "#1a1a1a",
      "pong-sport-primary-light": "#fef08a",
      "pong-sport-accent-light": "#fef9c3",
      "pong-sport-bg-light": "#f5f5f5",
      "pong-sport-surface-light": "#ffffff",
      "pong-sport-muted": "#737373",
      "pong-footer": "#262626",
      "pong-dark-custom": "#000000",
      "pong-error": "#ef4444",
      "pong-success": "#22c55e",
      "pong-warning": "#f59e0b",
      "pong-info": "#3b82f6",
      // === NEON SARI/ALTIN RENKLER ===
      "neon-pink": "#fbbf24",
      "neon-purple": "#f59e0b",
      "neon-blue": "#eab308",
      "neon-cyan": "#fcd34d",
      "neon-green": "#22c55e",
      "glass-bg": "rgba(0, 0, 0, 0.9)",
      "glass-border": "rgba(251, 191, 36, 0.3)",
    },
    keyframes: {
      fadeInUp: {
        "0%": { opacity: 0, transform: "translateY(20px)" },
        "100%": { opacity: 1, transform: "translateY(0)" },
      },
      blurIn: {
        "0%": { filter: "blur(4px)", opacity: 0 },
        "100%": { filter: "blur(0)", opacity: 1 },
      },
      backgroundPan: {
        "0%": { backgroundPosition: "0% 0%" },
        "100%": { backgroundPosition: "100% 100%" },
      },
      myFloat: {
        "0%, 100%": { transform: "translateY(0)" },
        "50%": { transform: "translateY(-10px)" },
      },
      myPulse: {
        "0%": { opacity: 1 },
        "50%": { opacity: 0.7 },
      },
      glow: {
        "0%": { boxShadow: "0 0 2px #fbbf24, 0 0 4px #fbbf24" },
        "33%": { boxShadow: "0 0 8px #fbbf24, 0 0 16px #fbbf24" },
        "66%": { boxShadow: "0 0 12px #fbbf24, 0 0 24px #fbbf24" },
        "100%": { boxShadow: "0 0 2px #fbbf24, 0 0 4px #fbbf24" },
      },
      neonPulse: {
        "0%, 100%": { boxShadow: "0 0 5px #fbbf24, 0 0 10px #fbbf24, 0 0 20px #fbbf24" },
        "50%": { boxShadow: "0 0 10px #f59e0b, 0 0 20px #f59e0b, 0 0 40px #f59e0b" },
      },
      shimmer: {
        "0%": { backgroundPosition: "-200% 0" },
        "100%": { backgroundPosition: "200% 0" },
      },
      gradientShift: {
        "0%, 100%": { backgroundPosition: "0% 50%" },
        "50%": { backgroundPosition: "100% 50%" },
      },
      slideIn: {
        "0%": { opacity: 0, transform: "translateY(50%)" },
        "100%": { opacity: 1, transform: "translateY(0)" },
      },
      opacity: {
        "0%": { opacity: 0 },
        "100%": { opacity: 1 },
      },
    },
    animation: {
      fadeInUp: "fadeInUp 0.8s ease-out",
      blurIn: "blurIn 0.6s ease-out forwards",
      backgroundPan: "backgroundPan 20s linear infinite",
      myFloat: "myFloat 3s ease-in-out infinite",
      myPulse: "myPulse 1.3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      glow: "glow 2s infinite ease-in-out",
      slideIn: "slideIn 0.5s ease-out forwards",
      opacity: "opacity 0.5s ease-in-out forwards",
      neonPulse: "neonPulse 2s ease-in-out infinite",
      shimmer: "shimmer 2s linear infinite",
      gradientShift: "gradientShift 3s ease infinite",
    },
  },
};
